version: '3.3'
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb1:/data/db
    environment:
      - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=1
  
  volumes:
    mongodb1:
      driver: local

