version: '3.3'
services:
  elastic:
    image: elasticsearch:6.5.1
    restart: always
    container_name: elastic_sherlock
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    volumes:
      - elastic1:/data/es-data
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - bootstrap.memory_lock=true
      - cluster.name=es-prod-docker-sherlock
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"

  volumes:
    elastic1:
      driver: local

