version: '3'
services:
    postgres:
        image: postgres:9.6
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=12qwaszx
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - ./sql/init.sh:/docker-entrypoint-initdb.d/init.sh
